name: layout_basics1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  flutter_stripe: ^11.3.0
  path_provider: ^2.0.14
  font_awesome_flutter: ^10.2.1
  json_editor_flutter: ^1.1.0
  focusable_control_builder: ^1.0.0
  cupertino_icons: ^1.0.5
  web_socket_channel: ^3.0.1
  http: ^1.2.2
  flutter_stripe_web: ^6.3.0
  url_launcher: ^6.3.1
  carousel_slider: ^4.2.1 # Add/Update this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
