name: layout_basics1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  path_provider: ^2.1.4
  path_provider_android: ^2.0.7 
  path_provider_ios: ^2.0.7 
  font_awesome_flutter: ^10.1.0
  json_editor_flutter: ^1.0.2

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Add your assets here
  assets:
    - assets/
    - assets/images/
    
